# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # npm install
    - name: npm install
      run: |
        npm install -g hexo-cli
        npm install
      env:
        CI: true
    # build
    - name: hexo build
      run: |
        hexo clean
        hexo generate
      env:
        CI: true
        
        
    # Deploy
  - name: Deploy
    uses: easingthemes/ssh-deploy@v2.0.7
    env:
      SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
      ARGS: "-avz --delete"
      SOURCE: "public/"
      REMOTE_HOST: http://81.69.12.254
      REMOTE_USER: root
      TARGET: /www/wwwroot/web/engine
