name: CI
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      # npm run build
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 打包
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ASSESS_TOKEN }}
          REMOTE_USER: "root"
          REMOTE_HOST: "81.69.12.254"
          SOURCE: "dist"
          TARGET: "/www/wwwroot/web/engine"
