name: CI
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # npm run build
      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      # 打包
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ASSESS_TOKEN }}
          REMOTE_USER: "root"
          REMOTE_HOST: "81.69.12.254"
          SOURCE: "dist"
          TARGET: "/www/wwwroot/web/engine"
