name: CI
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # npm run build
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 打包
      - name: Deploy
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          USERNAME: "root"
          HOST: "http://81.69.12.254"
          SSH_PRIVATE_KEY: ${{ secrets.ASSESS_TOKEN }}
          SOURCE: "dist"
          TARGET: "/www/wwwroot/web/engine"
